apiVersion: apps/v1
kind: Deployment
metadata:
  name: poke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poke
  template:
    metadata:
      labels:
        app: poke
    spec:
      containers:
      - image: okteto.dev/poke:latest
        name: poke
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e3a888b2-7952-46d2-9fa4-759b61642d15"
        - name: Vless_Path
          value: "/tvbmbmryhrdxe"
        - name: Vmess_UUID
          value: "e3a888b2-7952-46d2-9fa4-759b61642d15"
        - name: Vmess_Path
          value: "/wdcbkewsxzkhotx"
        - name: Share_Path
          value: "/v2link"
