apiVersion: apps/v1
kind: Deployment
metadata:
  name: posvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posvm
  template:
    metadata:
      labels:
        app: posvm
    spec:
      containers:
      - image: okteto.dev/posvm:latest
        name: posvm
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "dd3fc557-85c4-460b-992d-9ca47ef77f92"
        - name: Vless_Path
          value: "/tvbrfvwxnvkyf"
        - name: Vmess_UUID
          value: "dd3fc557-85c4-460b-992d-9ca47ef77f92"
        - name: Vmess_Path
          value: "/mkdcmkwzazkhotx"
        - name: Share_Path
          value: "/v2link"
