apiVersion: apps/v1
kind: Deployment
metadata:
  name: reet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reet
  template:
    metadata:
      labels:
        app: reet
    spec:
      containers:
      - image: okteto.dev/reet:latest
        name: reet
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "72d734b5-bc2d-4151-bc3b-ea364ae8cbe0"
        - name: Vless_Path
          value: "/tvbrfvnksrdxe"
        - name: Vmess_UUID
          value: "72d734b5-bc2d-4151-bc3b-ea364ae8cbe0"
        - name: Vmess_Path
          value: "/mkfvtsdsxzkhotx"
        - name: Share_Path
          value: "/v2link"
